### ISSUE TITLE
normal interface to call with input and returning filtered output

### ISSUE THREAD

**Issue by QingweiLau** [tomlankhorst/biquad#2]
Hi,
Which is the function I should call after defining a biquad or biquadchain instance to input my discritized signal and get the filtered signal, I cannot find it.

Thank you very much.

**Comment by QingweiLau** [comment]
sorry is it L47 of biquad.cpp,
https://github.com/tomlankhorst/biquad/blob/011413bc6fe56b85d28fc3174b8b01160e8e51b4/BiQuad.cpp#L47
I thought the step means step impulse LOL.

**Comment by tomlankhorst** [comment]
Also check the header file, which has all public functions documented. 

https://github.com/tomlankhorst/biquad/blob/master/BiQuad.h
